INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Blanca', 'Martinez', 'blanca@mail.com', '2018-06-12');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Cata', 'Perejil', 'cata@mail.com', '2018-06-12');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Juana', 'De Arco', 'juana@mail.com', '2018-06-12');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Tomás', 'De Aquino', 'tomas@mail.com', '2018-06-12');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Aristóteles', 'De Atenas', 'aristoteles@mail.com', '2018-06-12');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Leucipo', 'Matacarrillo', 'leucipo@mail.com', '2018-06-12');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Demócrito', 'De Alejandría', 'democrito@mail.com', '2018-06-12');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Marco', 'Aurelio', 'marco@mail.com', '2018-06-12');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Félix', 'Cuevas', 'felix@mail.com', '2018-06-12');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Juan', 'De Arimatea', 'juan.arimatea@mail.com', '2018-06-12');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Maria', 'San Juan', 'maria@mail.com', '2018-06-12');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('John', 'Doe', 'john@mail.com', '2018-06-12');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Hugo', 'Sanchez', 'hugo@mail.com', '2018-06-12');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Jorge', 'Campos', 'jorge@mail.com', '2018-06-12');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Jared', 'Borgetti', 'jared@mail.com', '2018-06-12');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Francisco', 'Fonseca', 'francisco@mail.com', '2018-06-12');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Juan', 'Pérez', 'juan@mail.com', '2018-06-12');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Ilena', 'Hiridia', 'ileana@mail.com', '2018-06-12');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Platón', 'De Atenas', 'platon@mail.com', '2018-06-12');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Gregorio', 'Magno', 'gregorio@mail.com', '2018-06-12');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Ines', 'De La Cruz', 'ines@mail.com', '2018-06-12');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Javier', 'Hernández', 'javier@mail.com', '2018-06-12');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Carlos', 'Vela', 'carlos@mail.com', '2018-06-12');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Miguel', 'Hidalgo', 'miguel@mail.com', '2018-06-12');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Pancho', 'Villa', 'pancho@mail.com', '2018-06-12');
INSERT INTO clientes(nombre, apellido, email, create_at) VALUES('Gustavo', 'A. Madero', 'gustavo@mail.com', '2018-06-12');